# CMake generated Testfile for 
# Source directory: /home/runner/work/akbench/akbench/akbench
# Build directory: /home/runner/work/akbench/akbench/_codeql_build_dir/akbench
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[barrier_test_constructor]=] "/home/runner/work/akbench/akbench/_codeql_build_dir/akbench/barrier_test" "--test-type=constructor")
set_tests_properties([=[barrier_test_constructor]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;42;add_test;/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;0;")
add_test([=[barrier_test_wait_with_random_sleep]=] "/home/runner/work/akbench/akbench/_codeql_build_dir/akbench/barrier_test" "--test-type=wait_with_random_sleep" "--num-iterations=3")
set_tests_properties([=[barrier_test_wait_with_random_sleep]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;44;add_test;/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;0;")
add_test([=[barrier_test_wait_without_sleep]=] "/home/runner/work/akbench/akbench/_codeql_build_dir/akbench/barrier_test" "--test-type=wait_without_sleep" "--num-iterations=3")
set_tests_properties([=[barrier_test_wait_without_sleep]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;47;add_test;/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;0;")
add_test([=[aklog_test]=] "/home/runner/work/akbench/akbench/_codeql_build_dir/akbench/aklog_test")
set_tests_properties([=[aklog_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;52;add_test;/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;0;")
add_test([=[memcpy_bandwidth_test]=] "/home/runner/work/akbench/akbench/_codeql_build_dir/akbench/memcpy_bandwidth_test")
set_tests_properties([=[memcpy_bandwidth_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;57;add_test;/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;0;")
add_test([=[memcpy_mt_bandwidth_test]=] "/home/runner/work/akbench/akbench/_codeql_build_dir/akbench/memcpy_mt_bandwidth_test")
set_tests_properties([=[memcpy_mt_bandwidth_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;62;add_test;/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;0;")
add_test([=[tcp_bandwidth_test]=] "/home/runner/work/akbench/akbench/_codeql_build_dir/akbench/tcp_bandwidth_test")
set_tests_properties([=[tcp_bandwidth_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;66;add_test;/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;0;")
add_test([=[uds_bandwidth_test]=] "/home/runner/work/akbench/akbench/_codeql_build_dir/akbench/uds_bandwidth_test")
set_tests_properties([=[uds_bandwidth_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;70;add_test;/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;0;")
add_test([=[pipe_bandwidth_test]=] "/home/runner/work/akbench/akbench/_codeql_build_dir/akbench/pipe_bandwidth_test")
set_tests_properties([=[pipe_bandwidth_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;74;add_test;/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;0;")
add_test([=[fifo_bandwidth_test]=] "/home/runner/work/akbench/akbench/_codeql_build_dir/akbench/fifo_bandwidth_test")
set_tests_properties([=[fifo_bandwidth_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;78;add_test;/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;0;")
add_test([=[mq_bandwidth_test]=] "/home/runner/work/akbench/akbench/_codeql_build_dir/akbench/mq_bandwidth_test")
set_tests_properties([=[mq_bandwidth_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;82;add_test;/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;0;")
add_test([=[mmap_bandwidth_test]=] "/home/runner/work/akbench/akbench/_codeql_build_dir/akbench/mmap_bandwidth_test")
set_tests_properties([=[mmap_bandwidth_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;86;add_test;/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;0;")
add_test([=[shm_bandwidth_test]=] "/home/runner/work/akbench/akbench/_codeql_build_dir/akbench/shm_bandwidth_test")
set_tests_properties([=[shm_bandwidth_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;90;add_test;/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;0;")
add_test([=[atomic_latency_test]=] "/home/runner/work/akbench/akbench/_codeql_build_dir/akbench/atomic_latency_test")
set_tests_properties([=[atomic_latency_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;95;add_test;/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;0;")
add_test([=[atomic_rel_acq_latency_test]=] "/home/runner/work/akbench/akbench/_codeql_build_dir/akbench/atomic_rel_acq_latency_test")
set_tests_properties([=[atomic_rel_acq_latency_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;100;add_test;/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;0;")
add_test([=[barrier_latency_test]=] "/home/runner/work/akbench/akbench/_codeql_build_dir/akbench/barrier_latency_test")
set_tests_properties([=[barrier_latency_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;104;add_test;/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;0;")
add_test([=[condition_variable_latency_test]=] "/home/runner/work/akbench/akbench/_codeql_build_dir/akbench/condition_variable_latency_test")
set_tests_properties([=[condition_variable_latency_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;110;add_test;/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;0;")
add_test([=[semaphore_latency_test]=] "/home/runner/work/akbench/akbench/_codeql_build_dir/akbench/semaphore_latency_test")
set_tests_properties([=[semaphore_latency_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;115;add_test;/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;0;")
add_test([=[syscall_latency_test]=] "/home/runner/work/akbench/akbench/_codeql_build_dir/akbench/syscall_latency_test")
set_tests_properties([=[syscall_latency_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;119;add_test;/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;0;")
add_test([=[akbench_json_test]=] "/home/runner/work/akbench/akbench/akbench/akbench_json_test.sh" "/home/runner/work/akbench/akbench/_codeql_build_dir/akbench/akbench")
set_tests_properties([=[akbench_json_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;171;add_test;/home/runner/work/akbench/akbench/akbench/CMakeLists.txt;0;")
